// Command genactions is the single-source generator: it reads the embedded
// built-in action scripts (agent/internal/actions/stdlib/*.star) — the exact
// Starlark the agent EXECUTES — parses their `# @key value` front-matter, and
// emits a TypeScript module the web imports. This guarantees the action library
// shows byte-for-byte what runs; there is no hand-maintained second copy.
//
// Run from the repo root:
//
//	go run ./agent/cmd/genactions
//
// or with explicit paths:
//
//	go run ./agent/cmd/genactions -stdlib agent/internal/actions/stdlib -out apps/web/lib/builtin-actions.generated.ts
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// builtinMeta mirrors the TS BuiltinMeta shape. Field order + tags define the
// emitted JSON (encoding/json sorts map keys, so the output is deterministic).
type builtinMeta struct {
	Kind       string   `json:"kind"`
	Name       string   `json:"name"`
	Summary    string   `json:"summary"`
	Risk       string   `json:"risk"`
	Reversible string   `json:"reversible"`
	Targets    []string `json:"targets"`
	Source     string   `json:"source"` // executed body, front-matter stripped (detail view)
	Full       string   `json:"full"`   // verbatim .star incl. front-matter (fork into the editor)
}

func main() {
	stdlib := flag.String("stdlib", "agent/internal/actions/stdlib", "directory of *.star scripts")
	out := flag.String("out", "apps/web/lib/builtin-actions.generated.ts", "output TypeScript file")
	flag.Parse()

	entries, err := os.ReadDir(*stdlib)
	if err != nil {
		fatal("read stdlib dir: %v", err)
	}
	metas := map[string]builtinMeta{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".star") {
			continue
		}
		kind := strings.TrimSuffix(e.Name(), ".star")
		data, err := os.ReadFile(filepath.Join(*stdlib, e.Name()))
		if err != nil {
			fatal("read %s: %v", e.Name(), err)
		}
		m, err := parseScript(kind, string(data))
		if err != nil {
			fatal("%s: %v", e.Name(), err)
		}
		metas[kind] = m
	}
	if len(metas) == 0 {
		fatal("no *.star scripts found in %s", *stdlib)
	}

	body, err := json.MarshalIndent(metas, "", "  ")
	if err != nil {
		fatal("marshal: %v", err)
	}

	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by agent/cmd/genactions from agent/internal/actions/stdlib/*.star.\n")
	b.WriteString("// Do NOT edit by hand — run `go run ./agent/cmd/genactions` after changing a script.\n")
	b.WriteString("// These are the EXACT Starlark scripts the agent executes for each built-in action:\n")
	b.WriteString("// shown == executed, built-in == custom.\n\n")
	b.WriteString("export type BuiltinRisk = 'low' | 'medium' | 'high';\n")
	b.WriteString("export type BuiltinReversible = 'snapshot' | 'readonly' | 'none';\n\n")
	b.WriteString("export type BuiltinMeta = {\n")
	b.WriteString("  kind: string;\n")
	b.WriteString("  name: string;\n")
	b.WriteString("  summary: string;\n")
	b.WriteString("  risk: BuiltinRisk;\n")
	b.WriteString("  reversible: BuiltinReversible;\n")
	b.WriteString("  targets: string[];\n")
	b.WriteString("  /** the executed Starlark, front-matter stripped (detail view) */\n")
	b.WriteString("  source: string;\n")
	b.WriteString("  /** the verbatim .star incl. front-matter (fork into the editor) */\n")
	b.WriteString("  full: string;\n")
	b.WriteString("};\n\n")
	b.WriteString("export const BUILTIN_ACTIONS: Record<string, BuiltinMeta> = ")
	b.Write(body)
	b.WriteString(";\n")

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fatal("write %s: %v", *out, err)
	}
	fmt.Printf("genactions: wrote %d built-in action(s) to %s\n", len(metas), *out)
}

// parseScript extracts the `# @key value` front-matter and the executable body
// (front-matter directive lines stripped). Required keys: name, summary, risk,
// reversible, targets.
func parseScript(kind, src string) (builtinMeta, error) {
	m := builtinMeta{Kind: kind, Full: strings.TrimRight(src, "\n") + "\n"}
	lines := strings.Split(src, "\n")
	kept := make([]string, 0, len(lines))
	for _, ln := range lines {
		t := strings.TrimSpace(ln)
		if strings.HasPrefix(t, "# @") {
			rest := strings.TrimPrefix(t, "# @")
			key, val, _ := strings.Cut(rest, " ")
			val = strings.TrimSpace(val)
			switch key {
			case "name":
				m.Name = val
			case "summary":
				m.Summary = val
			case "risk":
				m.Risk = val
			case "reversible":
				m.Reversible = val
			case "targets":
				for _, p := range strings.Split(val, ",") {
					if p = strings.TrimSpace(p); p != "" {
						m.Targets = append(m.Targets, p)
					}
				}
			}
			continue // never emit directive lines into the shown source
		}
		kept = append(kept, ln)
	}
	m.Source = strings.TrimSpace(strings.Join(kept, "\n")) + "\n"
	if m.Targets == nil {
		m.Targets = []string{}
	}

	var missing []string
	if m.Name == "" {
		missing = append(missing, "@name")
	}
	if m.Summary == "" {
		missing = append(missing, "@summary")
	}
	if m.Risk == "" {
		missing = append(missing, "@risk")
	}
	if m.Reversible == "" {
		missing = append(missing, "@reversible")
	}
	if len(missing) > 0 {
		return m, fmt.Errorf("missing front-matter: %s", strings.Join(missing, ", "))
	}
	return m, nil
}

func fatal(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "genactions: "+format+"\n", a...)
	os.Exit(1)
}
