apiVersion: v2
name: rocketplane
description: Self-hosted, OpenTelemetry-native observability platform (Stub-Chart).
type: application
version: 0.0.0
appVersion: "0.0.0"
keywords:
  - observability
  - opentelemetry
  - clickhouse
  - tracing
  - metrics
  - logs
home: https://github.com/rocketplaneio/rocketplane
sources:
  - https://github.com/rocketplaneio/rocketplane
